version: '3.8'

services:
  infografias-app:
    build: .
    container_name: infografias_server
    ports:
      - "36000:36000"
    volumes:
      - .:/app
      - /app/node_modules
    shm_size: '2gb'
    environment:
      - NODE_ENV=development
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium